HOUSEHOLD_DATA_AND_QUESTIONS = [
    "respondent_id",
    "is_initial_respondent",
    "nombre",
    "city_id",
    "cp2",
    "cp4_1",
    "cp4_2",
    "cp6",
    "cp7",
    "cp8",
    "cp9",
    "cp10_a",
    "cp10_b",
    "cp11",
    "cp13",
    "cp14",
    "cp15_1",
    "cp15_2",
    "cp16",
    "cp17",
    "cp18",
    "cp19",
    "factor_cvnl",
]

DEMOGRAPHIC_CODES = {
    "cp2": "sexo",
    "city_id": "city",
    "cp4_1": "edad_anos",
    "factor_cvnl": "factor_cvnl",
}


QUESTIONS_COLUMNS_MAPPING = {
    "Unnamed: 0": "type",
    "ENCUESTA ASÍ VAMOS 2025": "q_num",
    "Unnamed: 2": "q_sub_num",
    "Unnamed: 3": "q_text",
}

MISSING_VALUES = [
    "",
    "NA",
    "N/A",
    "No aplica",
    "No sabe",
    "No contesta",
    777,
    7777,
    77777,
    888,
    8888,
    88888,
    999,
    9999,
    99999,
]

HOUSEHOLD_NUMERIC_QUESTIONS = [
    "cp2",
    "cp4_1",
    "cp4_2",
    "cp6",
    "cp7",
    "cp8",
    "cp9",
    "cp10_a",
    "cp10_b",
    "cp11",
    "cp13",
    "cp14",
    "cp15_1",
    "cp15_2",
    "cp16",
    "cp17",
    "cp18",
    "cp19",
    "factor_cvnl",
]

QUESTION_SECTIONS = {
    "generales": {"start": "cp1", "end": "cp7"},
    "educacion": {"start": "cp8", "end": "cp19"},
    "ocupacion": {"start": "p1", "end": "p9"},
    "movilidad": {"start": "p10", "end": "p51"},
    "vivienda": {"start": "p52", "end": "p68"},
    "medio_ambiente": {"start": "p69", "end": "p85"},
    "economia": {"start": "p86", "end": "p88"},
    "discriminacion": {"start": "p89", "end": "p91"},
    "salud": {"start": "p92", "end": "p110"},
    "seguridad": {"start": "p111", "end": "p127"},
    "gobierno": {"start": "p128", "end": "p167"},
}

AGE_BINS = [0, 17, 24, 34, 44, 54, 64, 74, 999]
AGE_LABELS = ["0-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65-74", "75 o más"]

NUMERICAL_VALUE_QUESTIONS = [
    "cp1",
    "cp4_1",
    "cp4_2",
    "p3_1",
    "p3_2",
    "p4",
    "p7_1",
    "p7_2",
    "p8_1",
    "p8_2",
    "p9_1",
    "p9_2",
    "p18",
    "p20_1",
    "p20_2",
    "p21_1",
    "p21_2",
    "p24",
    "p25",
    "p26",
    "p27_1",
    "p27_2",
    "p28_1",
    "p28_2",
    "p46",
    "p49",
    "p50",
    "p56",
    "p103_1",
    "p103_2",
    "TIEMPO_TRABAJO",
    "PRESTACIONES", 
    "TRABAJO_FORMAL",   
    "QUEHACERES_HOGAR", 
    "CUIDADOS_PERSONAS",    
    "TOTAL_MIN_TRABAJO_REM_Y_NOREM",    
    "OCIO", 
    "TIEMPO_ESPERA_CONSULTA",
    "AL_MENOS_UN_PROBLEMA_MENTAL",
    #"RANGOS_EDAD",
    "TIEMPO_ESPERA",
    "COSTO_TOTAL_VIAJE_REDONDO",
    "TIEMPO_IDA",
    "TIEMPO_REGRESO",
    "TIEMPO_TOTAL_TRASLADO",
    "USA_TRANSPORTE_PUBLICO",
    "USA_METRO",
    "VICTIMA_TP",
    "TIEMPO_CAMINA",
    "NUM_DISCRIMINACIONES",
    "AL_MENOS_UNA_DISCRIMINACION",
    "NUM_ACCIONES_PC",
    "AL_MENOS_UNA_ACCION_PC"
]

AMM_ID = [6, 9, 21, 18, 26, 31, 39, 46, 19, 48, 49]
PERIFERIA_ID = [10, 12, 25, 41, 45]

ID_TO_CITY_NAME = {
    39: "Monterrey",
    26: "Guadalupe",
    46: "San Nicolás de los Garza",
    6: "Apodaca",
    21: "Escobedo",
    19: "San Pedro Garza García",
    49: "Santiago",
    31: "Juárez",
    18: "García",
    48: "Santa Catarina",
    9: "Cadereyta",
    41: "Pesquería",
    10: "El Carmen",
    12: "Ciénega de Flores",
    25: "Zuazua",
    45: "Salinas Victoria",
    1: "Abasolo",
    2: "Agualeguas",
    4: "Allende",
    5: "Anáhuac",
    7: "Aramberri",
    8: "Bustamante",
    11: "Cerralvo",
    13: "China",
    14: "Doctor Arroyo",
    15: "Doctor Coss",
    16: "Doctor González",
    17: "Galeana",
    20: "General Bravo",
    22: "General Terán",
    23: "General Treviño",
    24: "General Zaragoza",
    47: "Hidalgo",
    28: "Higueras",
    29: "Hualahuises",
    30: "Iturbide",
    31: "Juárez",
    32: "Lampazos de Naranjo",
    33: "Linares",
    3: "Los Aldamas",
    27: "Los Herreras",
    42: "Los Ramones",
    34: "Marín",
    35: "Melchor Ocampo",
    36: "Mier y Noriega",
    37: "Mina",
    38: "Montemorelos",
    40: "Parás",
    43: "Rayones",
    44: "Sabinas Hidalgo",
    50: "Vallecillo",
    51: "Villaldama",
    100: "Fuera de Nuevo León",
    111: "Fuera del País",
    8888: "No sabe",
    9999: "No contesta",
}
